version: '3'
services:
  postgres:
    image: 'postgres'
    container_name: 'postgres'
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d  # Mount the init directory
    networks:
      - code-challenge-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - code-challenge-network

volumes:
  db-data:
    driver: local

networks:
  code-challenge-network:
    driver: bridge